name: xgboost
channels:
  - conda-forge
dependencies:
  - py-xgboost-gpu
  - h5py
  - pytables
  - ipykernel
  - pip
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - more-itertools
  - iminuit
  - uproot
  - tqdm

