name: python2
dependencies:
  - nomkl
  - jupyterlab
  - pip
  - pandas
  - numpy
  - scipy
  - cudatoolkit=9.0
  - tensorflow
  - h5py
  - pytables
  - ipykernel
  - pip
  - pandas
  - numpy
  - scipy
  - scikit-learn
