name: tensorflow
channels:
  - conda-forge
dependencies:
  - cudatoolkit=9.0
  - tensorflow
  - h5py
  - pytables
  - ipykernel
  - pip
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - more-itertools
  - iminuit
  - uproot
  - keras
  - tqdm
