name: pytorch
channels:
  - conda-forge
dependencies:
  - pytorch
  - h5py
  - pytables
  - ipykernel
  - pip
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - iminuit
  - uproot
  - tqdm
